import Link from "next/link";
import { ChakraProvider } from "@chakra-ui/react";
import Provider from "./Provider";
import Header from "./Header";
import Main from "./Main";
import Footer from "./Footer";
import Loading from "./loading";
import Error from "./error";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // themeColor: "black",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <Header />
          <Main>
            <ErrorBoundary fallback={<Error />}>
              <Suspense fallback={<Loading />}>
                {children}
              </Suspense>
            </ErrorBoundary>
          </Main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
